title: Tom Vincent
description: Essays on hacking, travel and self-improvement
url: "https://tlvince.com"
safe: true
permalink: ":title"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "post"

exclude:
  - scripts
  - node_modules
  - package.json
  - package-lock.json

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-relative-links
